
[packages.darwin]
brews = [
"atuin",
"bash",
"calc",
"curl",
"dua-cli",
"fish",
"fnox",
"fzf",
"gh",
"git",
"jj",
"jq",
"kubernetes-cli",
"mise",
"pre-commit",
"qrencode",
"rink",
"ripgrep",
"rustup",
"semgrep",
"uv",
"watch",
"watchman",
"zoxide",
]
casks = [
"font-ibm-plex",
"font-jetbrains-mono",
"hiddenbar",
"jetbrains-toolbox",
"lunar",
"notunes",
"raycast",
"secretive",
]
